tp-text: 'ยง7Welcome to the spawn!'
spawn-text: 'ยง7Teleporting to the spawn, stand still...'
no-move: 'ยง4Teleportation cancelled!'
spawn-time: 5
server-time: 900
spawn-cooldown-perm: "serverspawn.cooldown"
respawn-bed-override: false
server:
  ==: org.bukkit.Location
  world: hub
  x: -61.5
  y: 70.0
  z: 6.5
  yaw: 180.41762
  pitch: -0.6275362
command:
  ==: org.bukkit.Location
  world: hub
  x: -61.5
  y: 70.0
  z: 6.5
  yaw: 180.41762
  pitch: -0.6275362
first:
  ==: org.bukkit.Location
  world: hub
  x: -61.5
  y: 70.0
  z: 6.5
  yaw: 180.41762
  pitch: -0.6275362
respawn:
  ==: org.bukkit.Location
  world: hub
  x: -61.5
  y: 70.0
  z: 6.5
  yaw: 180.41762
  pitch: -0.6275362
void:
  hub:
    ==: org.bukkit.Location
    world: hub
    x: -61.5
    y: 70.0
    z: 6.5
    yaw: 180.41762
    pitch: -0.6275362
